import { type VotersListRegistrationRequest, type VotersListUpdateRequest } from './types.js';
interface FormattedRegisterRequest {
    VoterID?: number;
    PropertyID?: number;
    FirstName: string;
    LastName: string;
    MiddleName: string;
    Year: string;
    Month: string;
    Day: string;
    Email: string;
    Gender: string;
    SchoolSupport: string;
    Citizenship: string;
    OccupancyStatus: string;
    Religion: string;
    ResidencyStatus: string;
    FrenchLanguageRights: string;
    DriversLicenceNumber?: string;
    SIN?: string;
    CertifyAccuracy: true;
    AddressType: 'C';
    MailingAddress1: string;
    MailingAddress2?: string;
    MailingAddress3?: string;
    MailingCity?: string;
    MailingProvince?: string;
    MailingPostalCode?: string;
    MailingCountry?: string;
    StreetNumber: string;
    StreetNumberSuffix?: string;
    StreetName: string;
    StreetType?: string;
    StreetDirection?: string;
    UnitNumber?: string;
    UnitType?: string;
    IPAddress?: string;
    UploadIDContent?: string;
    UploadIDFileName?: string;
    UploadID2Content?: string;
    UploadID2FileName?: string;
    UploadID3Content?: string;
    UploadID3FileName?: string;
    PreferEmailForContact?: 0 | 1 | 2;
    NotifyWhenProcessed?: boolean;
    AbsenteeVoteType: 0 | 1;
    AbsenteeAddress1?: string;
    AbsenteeAddress2?: string;
    AbsenteeAddress3?: string;
    AbsenteeCity?: string;
    AbsenteeProvince?: string;
    AbsenteePostalCode?: string;
    AbsenteeCountry?: string;
    PickUpBallot?: boolean;
    PickUpBallotName?: string;
}
export declare function formatRegisterRequest(request: VotersListRegistrationRequest | VotersListUpdateRequest): FormattedRegisterRequest;
export {};
